### ISSUE TITLE
Mixed content alert in firefox

### ISSUE THREAD

**Issue by vialibre** [cozy/cozy-controller#105]
Hei, my cozy instance shows a security warning for mixed content (Iceweasel 42, Cozy data-system 2.1.2).

What I expect is getting no security warning.

I believe the "Android app on google play" icon could be the reason for that, since it seems to be requested over http.
In any way, I don't feel really good with the idea that my cozy interface downloads an image from google.

Could a custom image hosted on the instance be used instead, or an option to remove that image ?

Thanks for your time,

**Comment by clochix** [comment]
Thanks a lot for reporting @vialibre.
This issue has been fixed but not published yet. We add an 's' to the image url ;-)

I understand your concern, but I don't think we can host this image ourselves, for legal reasons. Amha, for now, the easiest way not to download this image is to use a Firefox addon that allows to block contents.
