### ISSUE TITLE
Error with supervisor configuration file

### ISSUE THREAD

**Issue by cphyc** [cozy/cozy-controller#107]
In the installation process, when I try to launch supervisor, I get the following error:

    Error: Format string 'NODE_ENV=%(ENV_NODE_ENV)s' for 'environment' contains names which cannot be expanded

**Comment by clochix** [comment]
Hi @cphyc,

Thanks for giving Cozy a try ☺

Could you give us more infos on your configuration? How are you trying to install Cozy, on which OS?

**Comment by cphyc** [comment]
Hi,
I'm trying to install Cozy on a Debian Jessie. The installation through the deb package failed, so I tried to install it step by step.

It seems that either way, it is impossible to load the supervisor task correctly, thus making the installation process bug.

**Comment by clochix** [comment]
For the record, the step by step documentation is outdated and not really maintained anymore.

Do you remember which errors you saw when trying to install the debian package?

How are you trying to start the supervisor?

**Comment by nono** [comment]
FYI, the step by step documentation has been updated.

**Comment by nsteinmetz** [comment]
Hi,

I have the same error on my cubietruck using armbian jessie:

```
supervisord 
/usr/local/lib/python2.7/dist-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
Error: Format string 'NODE_ENV=%(ENV_NODE_ENV)s' for 'environment' contains names ('ENV_NODE_ENV') which cannot be expanded. Available names: ENV_ARCH, ENV_HOME, ENV_LANG, ENV_LANGUAGE, ENV_LC_MESSAGES, ENV_LOGNAME, ENV_MAIL, ENV_OLDPWD, ENV_PATH, ENV_PWD, ENV_SHELL, ENV_SHLVL, ENV_SSH_CLIENT, ENV_SSH_CONNECTION, ENV_SSH_TTY, ENV_TERM, ENV_USER, ENV_VDPAU_DRIVER, ENV__, group_name, here, host_node_name, process_num, program_name in section 'program:cozy-controller' (file: '/etc/supervisor/conf.d/cozy-controller.conf')
For help, use /usr/local/bin/supervisord -h
```

**Comment by clochix** [comment]
Thanks for reporting @nsteinmetz,

Could you edit file `/etc/supervisor/conf.d/cozy-controller.conf` and replace the line with `%(ENV_NODE_ENV)s` by:
```
environment=NODE_ENV="production"
```
The `ENV_NODE_ENV` syntax seems specific to our Docker scripts :-S

**Comment by nono** [comment]
I confirm, in cozy-docker, we inject `NODE_ENV` to supervisor when launching docker. So, we can use it for development and production. It was introduced by this commit: https://github.com/cozy-labs/cozy-docker/commit/18b79607ce6343770a61fb89a6d126a4c808d89f

**Comment by clochix** [comment]
Fixing the documentation is in progress: https://github.com/cozy/cozy-docs/pull/266

**Comment by nsteinmetz** [comment]
@clochix ok it works this way ; thanks and have a nice week-end !
