### ISSUE TITLE
ReferenceError: unit is not defined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-controller#112]
A self hosted user reports that the UI is unable to display its disk usage. In server logs, he see this error: `ReferenceError: unit is not defined in /usr/local/lib/node_modules/cozy-controller/build/server/controllers/disk.js`

Cf https://github.com/cozy/cozy-controller/blob/development/server/controllers/disk.coffee#L111

**Comment by khertan** [comment]
My couch local.conf : 
 
database_dir = /mnt/usb/cozy-data/ 

Command return : 

df -h /mnt/usb/cozy-data/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       917G  323G  548G  38% /mnt/usb

**Comment by poupotte** [comment]
Thanks @khertan  :)
