### ISSUE TITLE
Find a way to display error logs when an app is crashing.

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-controller#29]
Currently, application logging is stopped immediately after an app is crashing. It's like the controller doesn't let the app to tell what's wrong.

**Comment by frankrousseau** [comment]
That one must go higher in our priorities. Without that, it's too hard to debug apps in production mode.

**Comment by poupotte** [comment]
@frankrousseau , this problem should be fixed, is it ok for you ?

**Comment by frankrousseau** [comment]
I didn't have the opportunity yet to test it. Let's say it's ok. I will open a new issue, if the problem is still there.
