### ISSUE TITLE
Stack version is not updated correctly

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-controller#30]
I updated my stack from my Home, because the data system was out of date. It completed successfully (I now have the latest data-system version), but I still have the old version number.

**Comment by frankrousseau** [comment]
Is it still the case with the recent changes?

**Comment by poupotte** [comment]
It should be changed with #33

**Comment by jsilvestre** [comment]
I updated my Cozy this week-end, and didn't notice the issue. I close.
