### ISSUE TITLE
Problem during controller update

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-controller#39]
When controller is updated, if there is a npm problem, cozy doesn't restart.
Two solutions to limite this issue:
* Check if our cozy use our npm registry
* Retry controller update if it receives an error.

**Comment by frankrousseau** [comment]
We should retry the update. The update can be performed before the controller is shut down, while it's still running.

**Comment by poupotte** [comment]
After discussion with @LucsT, our cozy don't use anymore our npm registry due to npm improvements. Thus, I'll just add one (or two) retry in controller updating.
