### ISSUE TITLE
"Are you sure, you are root ?" should be reworded

### ISSUE THREAD

**Issue by yurivict** [cozy/cozy-controller#42]
This question is ambiguous, and can be understood in two mutually exclusive ways:
1. Are you sure that you are the root user?
2. Are you sure you want to run as root? (Implying that it can't run as root)

The third problem is that this is rhetoric question, process doesn't wait for an answer.

Better wording is: "cozy-controller should be run as root, current user is '<user-name>'"

**Comment by jsilvestre** [comment]
Thank you for the report, we'll change it.

**Comment by frankrousseau** [comment]
@yurivict It looks fixed. Could you check again?

**Comment by yurivict** [comment]
Yes, looks good!

**Comment by frankrousseau** [comment]
Great, thank you again!
