### ISSUE TITLE
missing things for docker compose 

### ISSUE THREAD

**Issue by athoune** [cozy/cozy-controller#47]
I need an option to listen 0.0.0.0

How can I setup indexer address and couchdb address?

**Comment by aenario** [comment]
- For the controller, you can set the HOST env variable to "0.0.0.0"
- For couchdb, you need to set bind_address in /usr/local/etc/couchdb/local.ini
- For the indexer, feel free to make a PR so [this line](https://github.com/cozy/cozy-data-indexer/blob/769beadfc5841b61b049fd2d2c7eb362467a5bb0/server.py#L18) depends on an env variable.

**Comment by athoune** [comment]
The other way.
For now, the controller can't find couchdb or the indexer. That's correct, they are no more localhost.
How can I configure the controller to tell it where couhedb and indexer are?

**Comment by aenario** [comment]
Ah, ok. My bad. So ...

## The controller only need to speak with couchdb (not the indexer)
You will need to make a PR [here](https://github.com/cozy/cozy-controller/blob/648e32ca5f3f8a67164bf829f83a81c1f57f5e4d/server/lib/autostart.coffee#L12)

## The DataSystem needs to speak with the indexer and couchdb
- it obeys COUCH_HOST & COUCH_PORT
- to change indexer host, you will need to make a PR [there](https://github.com/cozy/cozy-data-system/blob/31da9d6bda60b0d527da3306fa5a435bf69e65d3/server/lib/indexer.coffee#L10)

To pass env variables to the datasystem through the cozy-controller config file.
 /etc/cozy/controller.json
```
{"env":{"data-system": {"COUCH_HOST":"0.0.0.0"}}}
```

**Comment by frankrousseau** [comment]
@athoune For your first version, I think you should simplify the problem by ignoring the indexer.

**Comment by nono** [comment]
Some contributors are using cozy-cloud with docker compose. See https://forum.cozy.io/t/docker-smaller-images/1162
