### ISSUE TITLE
Unauthentified app + Install error won't stop the app from running

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-controller#67]
When installing Kresus on my hosted CC instance (benj.), I get some weird errors which look timely related. In particular, the installation aborts with "this app is broken, try to reinstall it". However, the logs are still filling up (with the installation of Weboob) !
Also, there are plenty of error messages in the log, due to the fact that the app isn't authentified: 
```
error when saving temporary log: Error when reading setting weboob-log: Error: { error: 'Application is not authenticated' }
```

"Unfortunately", when I've retried, the error didn't show up anymore, so this might be an intermittent issue (who doesn't love race conditions!).

**Comment by poupotte** [comment]
Hi @bnjbvr ,

Your platform is updated ? (home: 2.0.3, DS: 2.0.5, Proxy: 2.0.1, Controller: 2.0.27).
If you have again this problem, can you check kresus access in database (curl on http://<id>:<pwd@localhost:5984/cozy/_design/access/_view/all) ?

**Comment by bnjbvr** [comment]
It happened again, with Konnectors this time.

```
Data System: 2.0.5
Proxy: 2.0.1
Home: 2.0.3
Controller: 2.0.27
```

There is a konnectors entry in the "Access" table of the DS, and it doesn't seem to contain anything weird. Could it be that this entry in the DS is inserted **after** the application gets started? (Race conditions are such a pain in async JS...)

**Comment by bnjbvr** [comment]
Once again, removing and reinstalling the app did the trick. Sorry I can't provide more hints here, it really seems to be an intermittent issue...

**Comment by bnjbvr** [comment]
I seem to have more chances reproducing the issue when updating an app by hand with `cozy-monitor update X`. Right thereafter, the problem tends to show up in the logs and restarting the app fixes it...

**Comment by poupotte** [comment]
Thanks , can you check your application in your database: `cozy-monitor curlcouch _design/application/_view/all | grep <app_name`
Have you only one document ? This document have a password ?

**Comment by bnjbvr** [comment]
I see one document, and it doesn't seem to have a password:

```
{"id":"7b0f070b2550c92d94da604544118467","key":"7b0f070b2550c92d94da604544118467","value":{"_id":"7b0f070b2550c92d94da604544118467","_rev":"32-bb81bd4baa1dc4e11db0c11018089614","name":"kresus","displayName":"Kresus","description":"Kresus' Personal Finance Manager","slug":"kresus","state":"installed","isStoppable":false,"date":"2015-05-06T07:37:53.406Z","color":null,"git":"https://github.com/bnjbvr/kresus.git","branch":"incoming","widget":null,"version":"0.5.2","needsUpdate":false,"docType":"Application","iconPath":null,"iconType":"svg","port":9876,"id":"7b0f070b2550c92d94da604544118467","favorite":true,"repository":{"type":"git","url":"https://github.com/bnjbvr/kresus.git"},"dir":"/usr/local/cozy/apps/kresus","user":"cozy-kresus","logFile":"/usr/local/var/log/cozy/kresus.log","server":"build/server.js","startScript":"/usr/local/cozy/apps/kresus/build/server.js","backup":"/usr/local/var/log/cozy/kresus.log-backup","_attachments":{"icon.svg":{"content_type":"image/svg+xml","revpos":30,"digest":"md5-rZkPaQzh21VyLKYyVOaD6w==","length":8985,"stub":true}}}}
```

**Comment by poupotte** [comment]
Ok, it seems correct :/

And if you check accesses, have you a document for kresus ?
`cozy-monitor curlcouch _design/access/_view/all | grep kresus`

**Comment by bnjbvr** [comment]
Yes. Does it matter that I've already restarted Kresus, and fixed the issue? I guess so...

**Comment by poupotte** [comment]
Hello @bnjbvr ,

Did you have some authentication issues since  my last changes (2 weeks ago) ?

**Comment by bnjbvr** [comment]
I think so, but I am not quite sure. People on the forum saw it a few days ago, though.

**Comment by poupotte** [comment]
This issue seems fixed now.
