### ISSUE TITLE
controller installed as an application show as  "community"

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-controller#73]
While trying out the cozy command line I installed controller via ```cozy-monitor install controller```

now it show up in the Platform column but also in the Applications column. When I try to upgrade it in the applications column I get : 

![screenshot - 23072015 - 15 29 04](https://cloud.githubusercontent.com/assets/108437/8851439/c062d284-314f-11e5-8f50-6785ec9cfc71.png)

Not very reassuring for a core component of cozy.

**Comment by poupotte** [comment]
Hi @arthurlutz,

Actually, controller isn"t installed via cozy-monitor. Indeed, controller is used to install other application. `cozy-monitor` is just a tool to comunicate with controller. Thus, you have in your Cozy a controller installed by the controller :D .

The controller is installed by `npm -g install cozy-controller` and managed by supervirctl. If you want update it, you can : 
 * Click on `Update Platform` in state page
 * Update it with command line : `sudp npm -g update cozy-controller` and `sudo supervisorctl restart cozy-controller`.

I open an [issue](https://github.com/cozy/cozy-monitor/issues/90) to block controller installation via `cozy-monitor`.

I suggest you to uninstall your second controller installed via monitor (you can use home interface or cozy-monitor)

Zoé

**Comment by clochix** [comment]
@arthurlutz have you been able to uninstall the second controller ? If so, I suppose we could close this one. Thanks for your report !

**Comment by arthurlutz** [comment]
yep
