### ISSUE TITLE
Can install an invalid application

### ISSUE THREAD

**Issue by fflorent** [cozy/cozy-controller#79]
STR:
1. As the `cozy` user, run this command:  `cozy-monitor install https://github.com/bnjbvr/kresus`
2. You should see some error telling you it is an invalid application
3. Then run : `cozy-monitor status`
   => You should see `https://github.com/bnjbvr/kresus`

NOOOOO !
![](http://s3-ec.buzzfed.com/static/enhanced/web05/2011/12/7/17/anigif_enhanced-buzz-2749-1323295539-27.gif)

Florent

**Comment by clochix** [comment]
Thanks for reporting @fflorent 
FTR, the right syntax to install an app that isn't in the store is `cozy-monitor install kresus -r https://github.com/bnjbvr/kresus`

But you're right, we should better test the arguments of the install command. Also it seems that after this erroneous command, removing the broken app is difficult :-S

**Comment by fflorent** [comment]
> FTR, the right syntax to install an app that isn't in the store is `cozy-monitor install kresus -r https://github.com/bnjbvr/kresus`

Yeah, I know after reading the help :-/

Florent

**Comment by clochix** [comment]
@poupotte could you give us an update on the status of this one please?

**Comment by poupotte** [comment]
This issue should be fixed thanks to cozy/cozy-monitor#101

**Comment by clochix** [comment]
Thanks a lot !
