### ISSUE TITLE
Can't install an application with branch named like a folder in repository

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-controller#84]
**Example:**
I can't install cozy-home on branch `test` because there is a folder `test` on home repository.

**Cause:** 
We use `git checkout` to change repository branch : https://github.com/cozy/cozy-controller/blob/master/server/lib/git.coffee#L71

**Comment by clochix** [comment]
@poupotte what's the status of this issue please?

**Comment by poupotte** [comment]
This issue should be fixed.
